#!/usr/bin/env python3

# For more info, checkout: https://github.com/guyinatuxedo/itl

import os
import stat

if __name__ == "__main__":
    print("Installing itl (Inspire The Liars)")

    os.system("sudo apt-get install -y patchelf")

    originalItl = open("itl-original", "r")
    newItl = open("itl/itl.py", "w")

    line = originalItl.readline()
    while line:
    	# Write in the install directory
    	if "15935728" in line:
    		line = line.replace("15935728", os.getcwd())
    	newItl.write(line)
    	line = originalItl.readline()

    originalItl.close()
    newItl.close()

    os.system("python3 python-setup.py install")

